import type {
  Application,
  DeploymentEnvironment,
  PipelineDefinition,
  RunnerPool,
  SourceRepository,
} from "@deploy-management/shared";

export const SEED_REPOSITORIES: SourceRepository[] = [
  {
    id: "repo-mall-api",
    name: "mall-api",
    provider: "codeup",
    url: "https://codeup.aliyun.com/company/mall-api.git",
    defaultBranch: "main",
    branches: ["main", "develop", "release/2026.05", "hotfix/cart-timeout"],
    tags: ["v2026.05.08", "v2026.05.01", "v2026.04.28"],
    recentCommits: [
      { sha: "7d32f3ca9b18", message: "feat: release mall api canary", author: "林青", createdAt: "2026-05-11T06:28:00.000Z" },
      { sha: "1a778754db92", message: "fix: cart timeout retry", author: "陈澄", createdAt: "2026-05-10T14:10:00.000Z" },
      { sha: "c08b1fe42a71", message: "chore: update dependency lockfile", author: "RO", createdAt: "2026-05-09T09:40:00.000Z" },
    ],
    owner: "后端交付组",
  },
  {
    id: "repo-admin-web",
    name: "admin-web",
    provider: "codeup",
    url: "https://codeup.aliyun.com/company/admin-web.git",
    defaultBranch: "release/2026.05",
    branches: ["main", "develop", "release/2026.05", "feature/new-dashboard"],
    tags: ["web-2026.05.08", "web-2026.05.02"],
    recentCommits: [
      { sha: "d732f3c43caa", message: "feat: staging dashboard polish", author: "前端平台组", createdAt: "2026-05-11T05:36:00.000Z" },
      { sha: "af2b88469111", message: "fix: auth callback route", author: "RO", createdAt: "2026-05-10T11:24:00.000Z" },
      { sha: "43f2c954a02e", message: "perf: split admin chunks", author: "林青", createdAt: "2026-05-08T16:18:00.000Z" },
    ],
    owner: "前端平台组",
  },
  {
    id: "repo-payment",
    name: "payment",
    provider: "codeup",
    url: "https://codeup.aliyun.com/company/payment.git",
    defaultBranch: "main",
    branches: ["main", "develop", "hotfix/risk-gate", "release/2026.05"],
    tags: ["pay-2026.05.08", "pay-2026.04.30"],
    recentCommits: [
      { sha: "73ee5864fe20", message: "fix: payment risk gate timeout", author: "陈澄", createdAt: "2026-05-11T04:52:00.000Z" },
      { sha: "9d1fd14a55c2", message: "feat: canary payment rules", author: "交易稳定性组", createdAt: "2026-05-09T10:45:00.000Z" },
      { sha: "566b4a771099", message: "test: add settlement smoke cases", author: "RO", createdAt: "2026-05-07T12:02:00.000Z" },
    ],
    owner: "交易稳定性组",
  },
  {
    id: "repo-ops-agent",
    name: "ops-agent",
    provider: "gitlab",
    url: "https://gitlab.internal/platform/ops-agent.git",
    defaultBranch: "develop",
    branches: ["develop", "main", "feature/windows-runner"],
    tags: ["agent-1.8.0", "agent-1.7.4"],
    recentCommits: [
      { sha: "0f7a83b2bd55", message: "feat: windows runner bootstrap", author: "基础设施组", createdAt: "2026-05-10T03:30:00.000Z" },
      { sha: "23a4fd76a910", message: "fix: executor heartbeat", author: "RO", createdAt: "2026-05-08T08:08:00.000Z" },
    ],
    owner: "基础设施组",
  },
];

export const SEED_APPLICATIONS: Application[] = [
  {
    id: "mall-api",
    name: "商城 API",
    owner: "后端交付组",
    repositoryId: "repo-mall-api",
    repository: "https://codeup.aliyun.com/company/mall-api.git",
    defaultBranch: "main",
    language: "Node.js / Nest",
    serviceType: "Backend Service",
    environments: ["dev", "test", "staging", "prod"],
  },
  {
    id: "admin-web",
    name: "运营后台",
    owner: "前端平台组",
    repositoryId: "repo-admin-web",
    repository: "https://codeup.aliyun.com/company/admin-web.git",
    defaultBranch: "release/2026.05",
    language: "Next.js",
    serviceType: "Frontend App",
    environments: ["dev", "test", "staging", "prod"],
  },
  {
    id: "payment",
    name: "支付服务",
    owner: "交易稳定性组",
    repositoryId: "repo-payment",
    repository: "https://codeup.aliyun.com/company/payment.git",
    defaultBranch: "main",
    language: "Java / Spring Boot",
    serviceType: "Critical Service",
    environments: ["test", "staging", "prod"],
  },
];

export const SEED_PIPELINES: PipelineDefinition[] = [
  {
    id: "pipe-mall-prod",
    name: "mall-api-prod-release",
    applicationId: "mall-api",
    repositoryId: "repo-mall-api",
    repository: "https://codeup.aliyun.com/company/mall-api.git",
    defaultBranch: "main",
    defaultRefType: "branch",
    defaultRef: "main",
    sourcePolicy: {
      allowedBranchPatterns: ["main", "release/*", "hotfix/*"],
      allowedTagPatterns: ["v*"],
      allowRuntimeBranch: true,
      allowRuntimeTag: true,
      allowRuntimeCommit: true,
    },
    targetEnvironment: "prod",
    strategy: "canary",
    canaryPercent: 20,
    requiresApproval: true,
    stages: ["source", "test", "build", "env", "package", "upload", "deploy", "canary", "approval", "promote"],
    triggers: ["push main", "manual", "release tag"],
    owner: "后端交付组",
  },
  {
    id: "pipe-admin-staging",
    name: "admin-web-staging",
    applicationId: "admin-web",
    repositoryId: "repo-admin-web",
    repository: "https://codeup.aliyun.com/company/admin-web.git",
    defaultBranch: "release/2026.05",
    defaultRefType: "branch",
    defaultRef: "release/2026.05",
    sourcePolicy: {
      allowedBranchPatterns: ["release/*", "main", "feature/*"],
      allowedTagPatterns: ["web-*"],
      allowRuntimeBranch: true,
      allowRuntimeTag: true,
      allowRuntimeCommit: true,
    },
    targetEnvironment: "staging",
    strategy: "rolling",
    canaryPercent: 100,
    requiresApproval: false,
    stages: ["source", "test", "build", "env", "package", "upload", "deploy", "promote"],
    triggers: ["merge request", "manual"],
    owner: "前端平台组",
  },
  {
    id: "pipe-payment-prod",
    name: "payment-risk-gate",
    applicationId: "payment",
    repositoryId: "repo-payment",
    repository: "https://codeup.aliyun.com/company/payment.git",
    defaultBranch: "hotfix/risk-gate",
    defaultRefType: "branch",
    defaultRef: "hotfix/risk-gate",
    sourcePolicy: {
      allowedBranchPatterns: ["main", "hotfix/*", "release/*"],
      allowedTagPatterns: ["pay-*"],
      allowRuntimeBranch: true,
      allowRuntimeTag: false,
      allowRuntimeCommit: true,
    },
    targetEnvironment: "prod",
    strategy: "canary",
    canaryPercent: 10,
    requiresApproval: true,
    stages: ["source", "test", "build", "env", "package", "upload", "deploy", "canary", "approval", "promote"],
    triggers: ["manual", "change window"],
    owner: "交易稳定性组",
  },
];

export const SEED_ENVIRONMENTS: DeploymentEnvironment[] = [
  {
    id: "dev",
    name: "开发环境",
    cluster: "ack-dev-shanghai",
    protection: "自动部署",
    currentVersion: "2026.05.08-dev.12",
    status: "healthy",
    activeRuns: 3,
  },
  {
    id: "test",
    name: "测试环境",
    cluster: "ack-test-hangzhou",
    protection: "质量门禁",
    currentVersion: "2026.05.08-test.04",
    status: "warning",
    activeRuns: 1,
  },
  {
    id: "staging",
    name: "预发环境",
    cluster: "ack-staging-shanghai",
    protection: "冒烟通过",
    currentVersion: "2026.05.07-rc.3",
    status: "healthy",
    activeRuns: 2,
  },
  {
    id: "prod",
    name: "生产环境",
    cluster: "ack-prod-shanghai",
    protection: "审批 + 变更窗口 + 灰度观测",
    currentVersion: "2026.05.06-prod.9",
    status: "locked",
    activeRuns: 1,
  },
];

export const SEED_RUNNER_POOLS: RunnerPool[] = [
  { id: "runner-k8s", name: "k8s-linux-large", type: "kubernetes", online: 18, total: 24, queue: 6, cpuUsage: 72, memoryUsage: 64 },
  { id: "runner-win", name: "self-hosted-windows", type: "windows", online: 5, total: 8, queue: 2, cpuUsage: 48, memoryUsage: 55 },
  { id: "runner-secure", name: "vm-secure-build", type: "vm", online: 7, total: 10, queue: 1, cpuUsage: 38, memoryUsage: 42 },
];
